// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(MinitwitContext))]
    [Migration("20210211211641_followers")]
    partial class followers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Follower", b =>
                {
                    b.Property<int>("who_id")
                        .HasColumnType("int");

                    b.Property<int>("whom_id")
                        .HasColumnType("int");

                    b.Property<int?>("whomuser_id")
                        .HasColumnType("int");

                    b.Property<int?>("whouser_id")
                        .HasColumnType("int");

                    b.HasKey("who_id", "whom_id");

                    b.HasIndex("whomuser_id");

                    b.HasIndex("whouser_id");

                    b.ToTable("followers");
                });

            modelBuilder.Entity("Entities.Message", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<int?>("flagged")
                        .HasColumnType("int");

                    b.Property<int?>("pub_date")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("message_id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pw_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entities.Follower", b =>
                {
                    b.HasOne("Entities.User", "whom")
                        .WithMany()
                        .HasForeignKey("whomuser_id");

                    b.HasOne("Entities.User", "who")
                        .WithMany()
                        .HasForeignKey("whouser_id");

                    b.Navigation("who");

                    b.Navigation("whom");
                });
#pragma warning restore 612, 618
        }
    }
}
