name: .NET Tests

on:
  # Run on branch pushes
  push:
    branches: [ main ]
  # Run on pull requests
  pull_request:
  # Manual trigger
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Run tests and generate coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      working-directory: ./minitwit

    - name: ReportGenerator
      # You may pin to the exact commit or the version.
      # uses: danielpalme/ReportGenerator-GitHub-Action@51bdf1d37305906186a4dc09090faf716a3e3b44
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.8
      with:
        # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        reports: "minitwit/**/coverage.info"

    - name: coveralls Api
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: minitwit/Api.Test/coverage.info

    - name: coveralls Models
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: minitwit/Models.Test//coverage.info
