name: Infer# Analysis
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyse:
    name: Infer#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./minitwit
    - name: Build dotnet projects
      run: dotnet build --no-restore
      working-directory: ./minitwit
    - name: Dotnet Publish
      run: dotnet publish -c Release -o ./publish
      working-directory: ./minitwit/Api
    - name: Run Infer#
      uses: microsoft/infersharpaction@v1.0
      id: runinfersharp
      with:
        binary-path: './minitwit/Api/publish'
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
