name: Infer# Analysis
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyse:
    name: Infer#
    runs-on: ubuntu-latest
    steps:
      - name: Build dotnet projects
        run: dotnet build --no-restore
        working-directory: ./minitwit
      - name: Run Infer#
        uses: microsoft/infersharpaction@v1.0
        id: runinfersharp
        with:
          binary-path: './minitwit/Api/bin/Debug'
      - name: Infer# analysis results
        run: echo "${{ steps.runinfersharp.outputs.results }}"
